<a href="https://colab.research.google.com/github/Pidongg/pz286_ads_2024/blob/main/ads_course_assessment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assessment for Advanced Data Science
# *Data Pipelines*

## Radzim Sendyka, Christian Cabrera, Carl Henrik Ek and Neil D. Lawrence

### 19 November 2024

Welcome to the course assessment for the Advanced Data Science unit. In this assessment, you will build two data pipelines and prediction systems.

The maximum total mark for this assessment is 20. That mark is split into two miniprojects below.
- The first miniproject is worth 7 marks.
- The second miniproject is worth 13 marks.

*The check Session for this Assessment is 03 December 2024.*

# Task 1 (7 marks)

This example project builds on your experience from the practicals, using Open Street Maps, and connecting them to real-world datasets.

Your prediction system will be based on data from the 2021 UK Census, and Open Street Maps.


### Build a data pipeline and prediction system.

Structure your system around the [Access-Assess-Address](https://inverseprobability.com/talks/notes/access-assess-address-a-pipeline-for-automated-data-science.html) framework for automated data science.
Use the framework of [Data Readiness Levels](https://inverseprobability.com/publications/data-readiness-levels.html) to track the state of your datasets throughout the process.
Visualise your data and predictions using appropriate charts and graphics.
Remember, your notebook should tell a story.

1.1. Download the data from online sources. In this task you will need:
  - UK Census Data
    - The UK Census data file for and Socio-economic Classification (NS SEC) [here](https://www.ons.gov.uk/datasets/TS062/editions/2021/versions/5) or [here](https://www.nomisweb.co.uk/sources/census_2021_bulk). Use the most detailed area type (Output Areas).
    - One other UK Census data file of your choosing [here](https://www.ons.gov.uk/search?topics=9731,6646,3845,9497,4262,4128,7755,4994,6885,9724,7367&filter=datasets) or [here](https://www.nomisweb.co.uk/sources/census_2021_bulk). Use the most detailed area type available.
    - Geographic coordinates of Census Output Areas [here](https://www.data.gov.uk/dataset/4d4e021d-fe98-4a0e-88e2-3ead84538537/output-areas-december-2021-boundaries-ew-bgc-v2).
  - Spatial data
    - Set up an API connection to Open Street Maps [here](https://osmnx.readthedocs.io/en/stable/). Optionally, to be able to use more data in training, you might want to also download the entire map for England (or more) [here](https://download.openstreetmap.fr/extracts/) or [here](https://wiki.openstreetmap.org/wiki/Planet.osm).

1.2. Structure the data, and upload it to your AWS database.

- Census datasets can be huge and unwieldy to manipulate directly in python frameworks such as pandas. As a result we will host the data in a relational database.

- Using a cloud hosted database (such as MariaDB hosted on the AWS RDS service),  you will construct a database containing tables that contain per-output-area data, latitudes and longitudes of the output areas, and potentially, extracted selected open street maps features from the country-wide data file.

- Make sure you set the correct indices on your data, which will allow your code to run much faster. Hint: create an index on any columns you will be looking up, and joint indices if your lookup involves multiple columns (like coordinates).

You will likely find the following resources helpful.

- Lecture 1, 2 and 3.
- Lab class 1 and 2.


- *Note, this particular dataset could probably be handled directly in pandas, but you are explicitly tasked with using a database. This is a compromise from previous iterations of this course, where students spent quite a lot of time struggling from the size of the data. This is an opportunity for you to demonstrate your skills, as well as prepare for the second part of the assessment where databases might be necessary. Approach that do not use databases where needed will be penalised during marking.*


2.0. Explore the data.

  - To make predictions you will augment your data with information obtained from Open Street Map: an open license source of mapping information. You will need to use the techniques you have learnt in the course to indentify and incorporate useful features for your prediction tasks.
  - Look at the percentage of students (NS SEC code L15) in the individual output areas, and explore how it's related to various types of open street map features in those locations. Use the relationships you found to suggest the features to be used in a system that predicts percentage of students in a given area.
  - Do the same for an additional census variable (e.g., the average age in a given area).

3.0. Make a prediction system.
- Use Open Street Maps to predict Socio-Economic Status - in particular, the percent of full time students, from OSM features. Your function should take as input a coordinate pair (you can assume it will be in England), and return an estimate for the share of students in that area.

- Do the same for the additional census variable you selected in the previous step.

Hints:

  - *Some of the census data sheets are very detailed. You might want to try "boiling them down" to some aggregate value or selecting just the most important columns.*

  - *This assignment is focused on data pipelines, rather than machine learning, so we do not expect any advanced architectures here - a linear model or similar is perfectly fine.*
  
  - *For data exploration, or picking your second dataset, you may find useful the [interactive map](https://www.ons.gov.uk/census/maps/) of the census data.*

### Story.

- Remember the notebook you create should tell a story, any code that is not critical to that story can safely be placed into the associated analysis library and imported for use (structured as given in the Fynesse template). Make sure your decisions are well substanciated and flow nicely throughout the notebook, with clear explanations.

- Explain everything you do. Why is your question important, why you selected the datasets you did, why did you join them how you did, why did you look at the things you looked at.

Make sure in your notebook you discuss the design decisions you made in your pipeline and prediction system. How did you structure your notebook? How did you track data readiness? Which aspects of your system could be improved further?

Make sure you compare how you predict student population and your second chosen property. What differences are there, in the underlying data, process, and results?

Make sure you discuss the reusability of your data pipeline and prediction system. What changes to the underlying data/system is it resilient to, and what isn't it? What work would need to be done to adjust it to answer questions about other statistics, or a different country, instead?

### Fynesse library.

- Alongside your implementation you will provide a short repository overview describing how you have implemented the different parts of the project and where you have placed those parts in your code repository. You will submit your code alongside a version of this notebook that will allow your examiner to understand and reconstruct the thinking behind your analysis. This notebook is structured to help you in creating that description and allow you to understand how we will allocate the marks. You should make use of the Fynesse framework (https://github.com/lawrennd/fynesse_template) for structuring your code.

- One artefact to be included in your submission is a python library structured according to the "Access, Assess, Address" standard for data science solutions. You will submit this library alongside your code. Use the cell below to perform the necessary installation instructions for your library.
You should base your module on the template repository given by the Fynesse template repository. That should make it pip-installable as below.
`%pip install git+https://github.com/lawrennd/fynesse_template.git`. You can either replace fynesse with the name you've given your analysis module or you can leave the name as fynesse if you prefer.

- Remember the notebook you create should tell a story, any code that is not critical to that story can safely be placed into the associated analysis library and imported for use (structured as given in the Fynesse template). Remember to include you fynesse library in your submission.

## Access

In [6]:
# install your library here
%pip install git+https://github.com/Pidongg/pz286_ads_2024.git
%pip install osmnx

Collecting git+https://github.com/Pidongg/pz286_ads_2024.git
  Cloning https://github.com/Pidongg/pz286_ads_2024.git to /tmp/pip-req-build-pnxfjrgj
  Running command git clone --filter=blob:none --quiet https://github.com/Pidongg/pz286_ads_2024.git /tmp/pip-req-build-pnxfjrgj
  Resolved https://github.com/Pidongg/pz286_ads_2024.git to commit 01016e9262865704e390fb1847cca3dafef0c97b
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from fynesse==0.1.0) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from fynesse==0.1.0) (1.26.4)
Collecting jupyter (from fynesse==0.1.0)
  Using cached jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from fynesse==0.1.0) (3.8.0)
Requirement already satisfied: notebook in /usr/local/lib/python3.10/dist-packages (from jupyter->fynesse==0.1.0) (6.5.5)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.10/dist-packages (from jupyter->fynesse==0.1.0) (6.1.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.10/dist-packages (from jupyter->fynesse==0.1.0) (7.16.4)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.10/dist-packages (from jupyter->fynesse==0.1.0) (5.5.6)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (from jupyter->fynesse==0.1.0) (7.7.1)
Collecting jupyterlab (from jupyter->fynesse==0.1.0)
  Downloading jupyterlab-4.3.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (4.55.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (24.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->fynesse==0.1.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->fynesse==0.1.0) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->fynesse==0.1.0) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->fynesse==0.1.0) (1.16.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (0.2.0)
Requirement already satisfied: ipython>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (7.34.0)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (5.7.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (6.3.3)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->jupyter->fynesse==0.1.0) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets->jupyter->fynesse==0.1.0) (3.0.13)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-console->jupyter->fynesse==0.1.0) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from jupyter-console->jupyter->fynesse==0.1.0) (2.18.0)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter->fynesse==0.1.0)
  Downloading async_lru-2.0.4-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: httpx>=0.25.0 in /usr/local/lib/python3.10/dist-packages (from jupyterlab->jupyter->fynesse==0.1.0) (0.27.2)
Collecting ipykernel (from jupyter->fynesse==0.1.0)
  Downloading ipykernel-6.29.5-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.10/dist-packages (from jupyterlab->jupyter->fynesse==0.1.0) (3.1.4)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.10/dist-packages (from jupyterlab->jupyter->fynesse==0.1.0) (5.7.2)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter->fynesse==0.1.0)
  Downloading jupyter_lsp-2.2.5-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter->fynesse==0.1.0)
  Downloading jupyter_server-2.14.2-py3-none-any.whl.metadata (8.4 kB)
Collecting jupyterlab-server<3,>=2.27.1 (from jupyterlab->jupyter->fynesse==0.1.0)
  Downloading jupyterlab_server-2.27.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.10/dist-packages (from jupyterlab->jupyter->fynesse==0.1.0) (0.2.4)
Requirement already satisfied: setuptools>=40.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyterlab->jupyter->fynesse==0.1.0) (75.1.0)
Requirement already satisfied: tomli>=1.2.2 in /usr/local/lib/python3.10/dist-packages (from jupyterlab->jupyter->fynesse==0.1.0) (2.1.0)
Collecting comm>=0.1.1 (from ipykernel->jupyter->fynesse==0.1.0)
  Downloading comm-0.2.2-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: debugpy>=1.6.5 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (1.8.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (0.1.7)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (5.9.5)
Requirement already satisfied: pyzmq>=24 in /usr/local/lib/python3.10/dist-packages (from ipykernel->jupyter->fynesse==0.1.0) (24.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (0.10.0)
Requirement already satisfied: nbformat>=5.7 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (1.5.1)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert->jupyter->fynesse==0.1.0) (1.4.0)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->fynesse==0.1.0) (23.1.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->fynesse==0.1.0) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->fynesse==0.1.0) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->fynesse==0.1.0) (0.21.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook->jupyter->fynesse==0.1.0) (1.1.0)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from async-lru>=1.0.0->jupyterlab->jupyter->fynesse==0.1.0) (4.12.2)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach!=5.0.0->nbconvert->jupyter->fynesse==0.1.0) (0.5.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (1.0.7)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (3.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (0.14.0)
Collecting jedi>=0.16 (from ipython>=5.0.0->ipykernel->jupyter->fynesse==0.1.0)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=5.0.0->ipykernel->jupyter->fynesse==0.1.0) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=5.0.0->ipykernel->jupyter->fynesse==0.1.0) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=5.0.0->ipykernel->jupyter->fynesse==0.1.0) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=5.0.0->ipykernel->jupyter->fynesse==0.1.0) (4.9.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core->jupyterlab->jupyter->fynesse==0.1.0) (4.3.6)
Collecting jupyter-client (from jupyter-console->jupyter->fynesse==0.1.0)
  Downloading jupyter_client-7.4.9-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyter-events>=0.9.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading jupyter_events-0.10.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading jupyter_server_terminals-0.5.3-py3-none-any.whl.metadata (5.6 kB)
Collecting overrides>=5.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.10/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0) (1.8.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->notebook->jupyter->fynesse==0.1.0) (21.2.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.10/dist-packages (from jupyter-client->jupyter-console->jupyter->fynesse==0.1.0) (0.4)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.10/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (2.16.0)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading json5-0.9.28-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.10/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (4.23.0)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.10/dist-packages (from nbformat>=5.7->nbconvert->jupyter->fynesse==0.1.0) (2.20.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->jupyter-console->jupyter->fynesse==0.1.0) (0.2.13)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.10/dist-packages (from terminado>=0.8.3->notebook->jupyter->fynesse==0.1.0) (0.7.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert->jupyter->fynesse==0.1.0) (2.6)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx>=0.25.0->jupyterlab->jupyter->fynesse==0.1.0) (1.2.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel->jupyter->fynesse==0.1.0) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (0.21.0)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading python_json_logger-2.0.7-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.10/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0) (6.0.2)
Collecting rfc3339-validator (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter->fynesse==0.1.0) (2.2.3)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter->fynesse==0.1.0) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter->fynesse==0.1.0) (2.22)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.10/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0) (3.0.0)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0) (24.11.1)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading arrow-1.3.0-py3-none-any.whl.metadata (7.5 kB)
Collecting types-python-dateutil>=2.8.10 (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter->fynesse==0.1.0)
  Downloading types_python_dateutil-2.9.0.20241003-py3-none-any.whl.metadata (1.9 kB)
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading jupyterlab-4.3.1-py3-none-any.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 81.3 MB/s eta 0:00:00
Downloading ipykernel-6.29.5-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.2/117.2 kB 7.8 MB/s eta 0:00:00
Downloading async_lru-2.0.4-py3-none-any.whl (6.1 kB)
Downloading comm-0.2.2-py3-none-any.whl (7.2 kB)
Downloading jupyter_lsp-2.2.5-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 5.8 MB/s eta 0:00:00
Downloading jupyter_server-2.14.2-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 27.2 MB/s eta 0:00:00
Downloading jupyter_client-7.4.9-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 kB 10.7 MB/s eta 0:00:00
Downloading jupyterlab_server-2.27.3-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 4.5 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 49.4 MB/s eta 0:00:00
Downloading json5-0.9.28-py3-none-any.whl (30 kB)
Downloading jupyter_events-0.10.0-py3-none-any.whl (18 kB)
Downloading jupyter_server_terminals-0.5.3-py3-none-any.whl (13 kB)
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading python_json_logger-2.0.7-py3-none-any.whl (8.1 kB)
Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Downloading arrow-1.3.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.6 MB/s eta 0:00:00
Downloading types_python_dateutil-2.9.0.20241003-py3-none-any.whl (9.7 kB)
Building wheels for collected packages: fynesse
  Building wheel for fynesse (setup.py) ... done
  Created wheel for fynesse: filename=fynesse-0.1.0-py3-none-any.whl size=7883 sha256=78664fa0e58b32948e902b134915df2fe0ff648821d75d4fe15407db7d9c60f5

In [7]:
import pandas as pd
import numpy as np
import osmnx as ox
# TODO: more imports here
import fynesse
import yaml
from ipywidgets import interact_manual, Text, Password

In [8]:
%pip install pymysql
%load_ext sql

Requirement already satisfied: pymysql in /usr/local/lib/python3.10/dist-packages (1.1.1)
The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [9]:
@interact_manual(username=Text(description="Username:"),
                password=Password(description="Password:"),
                url=Text(description="URL:"),
                port=Text(description="Port:"))
def write_credentials(username, password, url, port):
    with open("credentials.yaml", "w") as file:
        credentials_dict = {'username': username,
                           'password': password,
                           'url': url,
                           'port': port}
        yaml.dump(credentials_dict, file)

interactive(children=(Text(value='', description='Username:'), Password(description='Password:'), Text(value='…

In [22]:
with open("credentials.yaml") as file:
  credentials = yaml.safe_load(file)
username = credentials["username"]
password = credentials["password"]
url = credentials["url"]
port = credentials["port"]

In [13]:
# [1] UK census data
import requests
import zipfile
import io
import os
import pandas as pd

def download_census_data(code, base_dir=''):
  url = f'https://www.nomisweb.co.uk/output/census/2021/census2021-{code.lower()}.zip'
  extract_dir = os.path.join(base_dir, os.path.splitext(os.path.basename(url))[0])

  if os.path.exists(extract_dir) and os.listdir(extract_dir):
    print(f"Files already exist at: {extract_dir}.")
    return

  os.makedirs(extract_dir, exist_ok=True)
  response = requests.get(url)
  response.raise_for_status()

  with zipfile.ZipFile(io.BytesIO(response.content)) as zip_ref:
    zip_ref.extractall(extract_dir)

  print(f"Files extracted to: {extract_dir}")

def load_census_data(code, level='oa'):
  return pd.read_csv(f'census2021-{code.lower()}/census2021-{code.lower()}-{level}.csv')

def get_df(code, level='oa'):
  download_census_data(code)
  return load_census_data(code, level)

In [14]:
full_time_student_df = get_df('TS062', level='oa')

Files extracted to: census2021-ts062

In [15]:
full_time_student_df

,date,geography,geography code,National Statistics Socio-economic Classification (NS-SEC): Total: All usual residents aged 16 years and over,"National Statistics Socio-economic Classification (NS-SEC): L1, L2 and L3 Higher managerial, administrative and professional occupations","National Statistics Socio-economic Classification (NS-SEC): L4, L5 and L6 Lower managerial, administrative and professional occupations",National Statistics Socio-economic Classification (NS-SEC): L7 Intermediate occupations,National Statistics Socio-economic Classification (NS-SEC): L8 and L9 Small employers and own account workers,National Statistics Socio-economic Classification (NS-SEC): L10 and L11 Lower supervisory and technical occupations,National Statistics Socio-economic Classification (NS-SEC): L12 Semi-routine occupations,National Statistics Socio-economic Classification (NS-SEC): L13 Routine occupations,National Statistics Socio-economic Classification (NS-SEC): L14.1 and L14.2 Never worked and long-term unemployed,National Statistics Socio-economic Classification (NS-SEC): L15 Full-time students
0,2021,E00000001,E00000001,159,80,38,13,9,3,5,5,4,2
1,2021,E00000003,E00000003,222,96,58,8,26,2,5,2,5,20
2,2021,E00000005,E00000005,103,37,28,8,21,0,3,1,1,4
3,2021,E00000007,E00000007,140,62,39,5,11,3,3,1,6,10
4,2021,E00000010,E00000010,170,34,45,17,27,7,10,14,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188875,2021,W00010693,W00010693,737,2,8,5,8,7,9,14,2,682
188876,2021,W00010694,W00010694,304,35,87,40,31,23,26,33,7,22
188877,2021,W00010695,W00010695,154,12,44,22,15,12,15,17,11,6
188878,2021,W00010696,W00010696,176,32,55,26,14,9,13,12,7,8
188879,2021,W00010697,W00010697,215,16,59,40,21,10,30,27,4,8

In [24]:
!pip install -U ipython-sql prettytable
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.10/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.10/dist-packages (3.12.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (2.0.36)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (0.5.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.10/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prettytable) (0.2.13)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.1.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (75.1.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)

In [25]:
%sql mariadb+pymysql://$username:$password@$url?local_infile=1
%sql SHOW databases

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
7 rows affected.

[('ads_2024',),
 ('information_schema',),
 ('innodb',),
 ('mysql',),
 ('performance_schema',),
 ('sys',),
 ('tmp',)]

In [26]:
%%sql
USE `ads_2024`;

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.

[]

In [ ]:
file_name = "./pp-2021-part2.csv"
data = pd.read_csv(file_name)
data.info(verbose=True)

In [30]:
full_time_student_df

,date,geography,geography code,National Statistics Socio-economic Classification (NS-SEC): Total: All usual residents aged 16 years and over,"National Statistics Socio-economic Classification (NS-SEC): L1, L2 and L3 Higher managerial, administrative and professional occupations","National Statistics Socio-economic Classification (NS-SEC): L4, L5 and L6 Lower managerial, administrative and professional occupations",National Statistics Socio-economic Classification (NS-SEC): L7 Intermediate occupations,National Statistics Socio-economic Classification (NS-SEC): L8 and L9 Small employers and own account workers,National Statistics Socio-economic Classification (NS-SEC): L10 and L11 Lower supervisory and technical occupations,National Statistics Socio-economic Classification (NS-SEC): L12 Semi-routine occupations,National Statistics Socio-economic Classification (NS-SEC): L13 Routine occupations,National Statistics Socio-economic Classification (NS-SEC): L14.1 and L14.2 Never worked and long-term unemployed,National Statistics Socio-economic Classification (NS-SEC): L15 Full-time students
0,2021,E00000001,E00000001,159,80,38,13,9,3,5,5,4,2
1,2021,E00000003,E00000003,222,96,58,8,26,2,5,2,5,20
2,2021,E00000005,E00000005,103,37,28,8,21,0,3,1,1,4
3,2021,E00000007,E00000007,140,62,39,5,11,3,3,1,6,10
4,2021,E00000010,E00000010,170,34,45,17,27,7,10,14,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188875,2021,W00010693,W00010693,737,2,8,5,8,7,9,14,2,682
188876,2021,W00010694,W00010694,304,35,87,40,31,23,26,33,7,22
188877,2021,W00010695,W00010695,154,12,44,22,15,12,15,17,11,6
188878,2021,W00010696,W00010696,176,32,55,26,14,9,13,12,7,8
188879,2021,W00010697,W00010697,215,16,59,40,21,10,30,27,4,8

In [33]:
max(full_time_student_df['National Statistics Socio-economic Classification (NS-SEC): Total: All usual residents aged 16 years and over'])

4463

In [29]:
full_time_student_df.dtypes

date                                                                                                                                         int64
geography                                                                                                                                   object
geography code                                                                                                                              object
National Statistics Socio-economic Classification (NS-SEC): Total: All usual residents aged 16 years and over                                int64
National Statistics Socio-economic Classification (NS-SEC): L1, L2 and L3 Higher managerial, administrative and professional occupations     int64
National Statistics Socio-economic Classification (NS-SEC): L4, L5 and L6 Lower managerial, administrative and professional occupations      int64
National Statistics Socio-economic Classification (NS-SEC): L7 Intermediate occupations                                                      int64
National Statistics Socio-economic Classification (NS-SEC): L8 and L9 Small employers and own account workers                                int64
National Statistics Socio-economic Classification (NS-SEC): L10 and L11 Lower supervisory and technical occupations                          int64
National Statistics Socio-economic Classification (NS-SEC): L12 Semi-routine occupations                                                     int64
National Statistics Socio-economic Classification (NS-SEC): L13 Routine occupations                                                          int64
National Statistics Socio-economic Classification (NS-SEC): L14.1 and L14.2 Never worked and long-term unemployed                            int64
National Statistics Socio-economic Classification (NS-SEC): L15 Full-time students                                                           int64
dtype: object

In [41]:
%%sql
--
-- Table structure for table `nssec_data`
--
USE `ads_2024`;
CREATE TABLE IF NOT EXISTS `nssec_fulltime_students_data` (
  `date` int(4) NOT NULL,
  `geography` varchar(9) COLLATE utf8_bin NOT NULL,
  `geography_code` varchar(9) COLLATE utf8_bin NOT NULL,
  `total_residents` int(10) unsigned NOT NULL,
  `higher_managerial` int(10) unsigned NOT NULL,
  `lower_managerial` int(10) unsigned NOT NULL,
  `intermediate_occupations` int(10) unsigned NOT NULL,
  `small_employers` int(10) unsigned NOT NULL,
  `lower_supervisory` int(10) unsigned NOT NULL,
  `semi_routine` int(10) unsigned NOT NULL,
  `routine_occupations` int(10) unsigned NOT NULL,
  `never_worked_unemployed` int(10) unsigned NOT NULL,
  `full_time_students` int(10) unsigned NOT NULL,
  PRIMARY KEY (`geography`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.
0 rows affected.

[]

In [42]:
%sql CREATE INDEX `idx_geography` ON nssec_fulltime_students_data(geography);

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.

[]

In [44]:
%sql LOAD DATA LOCAL INFILE "./census2021-ts062/census2021-ts062-oa.csv" INTO TABLE `nssec_fulltime_students_data` FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED by '"' LINES STARTING BY '' TERMINATED BY '\n';

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
188881 rows affected.

[]

In [45]:
url = "https://open-geography-portalx-ons.hub.arcgis.com/api/download/v1/items/6beafcfd9b9c4c9993a06b6b199d7e6d/csv?layers=0"
filename = "census_output_coordinates.csv"
response = requests.get(url)
with open(filename, "wb") as f:
    f.write(response.content)

In [50]:
census_output_coordinates_df = pd.read_csv(filename)

Upload geographic coordinates of census output areas data to ads_2024.

In [53]:
%%sql
--
-- Table structure for table `nssec_data`
--
USE `ads_2024`;
CREATE TABLE IF NOT EXISTS `nssec_output_areas_coordinates` (
  `FID` int(10) NOT NULL,
  `OA21CD` varchar(9) COLLATE utf8_bin NOT NULL,
  `LSOA21CD` varchar(9) COLLATE utf8_bin NOT NULL,
  `LSOA21NM` varchar(255) COLLATE utf8_bin NOT NULL,
  `LSOA21NMW` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `BNG_E` double NOT NULL,
  `BNG_N` double NOT NULL,
  `LAT` double NOT NULL,
  `LONG` double NOT NULL,
  `Shape__Area` double NOT NULL,
  `Shape__Length` double NOT NULL,
  `GlobalID` varchar(36) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`FID`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.
0 rows affected.

[]

In [54]:
%sql LOAD DATA LOCAL INFILE "./census_output_coordinates.csv" INTO TABLE `nssec_output_areas_coordinates` FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED by '"' LINES STARTING BY '' TERMINATED BY '\n';

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
188881 rows affected.

[]

In [55]:
%sql CREATE INDEX `idx_geography_code` ON nssec_output_areas_coordinates(OA21CD);

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.

[]

In [59]:
# remove first row in nssec_output_areas_coordinates and nssec_fulltime_students_data, in the database
%sql DELETE FROM nssec_output_areas_coordinates WHERE FID = 0;
%sql DELETE FROM nssec_fulltime_students_data WHERE `geography` = 'geography';

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
1 rows affected.
 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
1 rows affected.

[]

In [61]:
%sql CREATE INDEX `idx_oa_latitude_longitude` ON nssec_output_areas_coordinates(LAT,`LONG`);

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.

[]

In [52]:
census_output_coordinates_df.dtypes

FID                int64
OA21CD            object
LSOA21CD          object
LSOA21NM          object
LSOA21NMW         object
BNG_E              int64
BNG_N              int64
LAT              float64
LONG             float64
Shape__Area      float64
Shape__Length    float64
GlobalID          object
dtype: object

In [31]:
census_output_coordinates_df

,FID,OA21CD,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,Shape__Area,Shape__Length,GlobalID
0,1,E00000001,E01000001,City of London 001A,,532250,181864,51.52022,-0.09523,6949.151482,421.166161,3a44dd3d-5082-4a09-9b9c-3a5fadc811ed
1,2,E00000003,E01000001,City of London 001A,,532171,181819,51.51983,-0.09638,4492.411072,307.714653,f1216dc8-14d1-4857-9230-cab0641758fb
2,3,E00000005,E01000001,City of London 001A,,532166,181722,51.51896,-0.09649,8565.514214,385.204781,44d6f70f-549c-4288-9b6d-de2adbf02582
3,4,E00000007,E01000001,City of London 001A,,532088,181473,51.51674,-0.09771,75994.829704,1408.607657,4dd683e1-9a5c-46cf-9e19-8465c8fbb6cb
4,5,E00000010,E01000003,City of London 001C,,532092,182114,51.52250,-0.09741,2102.876602,215.271975,7476781f-8fe4-4c9b-bde1-0eecbd146dff
...,...,...,...,...,...,...,...,...,...,...,...,...
188875,188876,W00010693,W01000062,Gwynedd 001A,Gwynedd 001A,257885,371596,53.22236,-4.13012,117624.672455,2070.603553,5f872a8d-7128-47b4-a6ab-487a8aa93716
188876,188877,W00010694,W01000645,Carmarthenshire 006C,Sir Gaerfyrddin 006C,240146,220834,51.86313,-4.32295,261298.148006,3228.184286,69c22977-5117-45ee-89d5-0eb35fc713b1
188877,188878,W00010695,W01000664,Carmarthenshire 016C,Sir Gaerfyrddin 016C,256581,213406,51.80086,-4.08136,196049.177578,2232.955182,b511da17-e4e3-4425-bd9b-bea99d2c5071
188878,188879,W00010696,W01001923,Carmarthenshire 026G,Sir Gaerfyrddin 026G,252233,198463,51.66546,-4.13803,358656.479244,2928.234067,b36d2ac0-a236-4e97-8dc0-044327808718
188879,188880,W00010697,W01000667,Carmarthenshire 023C,Sir Gaerfyrddin 023C,249792,200786,51.68569,-4.17430,41479.260704,929.445832,b9f72baf-42b1-4da6-9be6-45c1a86cd3ef

download entire uk map

In [64]:
!wget https://download.openstreetmap.fr/extracts/europe/united_kingdom-latest.osm.pbf

--2024-11-25 00:13:17--  https://download.openstreetmap.fr/extracts/europe/united_kingdom-latest.osm.pbf
Resolving download.openstreetmap.fr (download.openstreetmap.fr)... 213.36.253.212, 2a01:e0d:1:c:58bf:fac1:0:14
Connecting to download.openstreetmap.fr (download.openstreetmap.fr)|213.36.253.212|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2185131210 (2.0G) [application/vnd.openstreetmap.data+xml]
Saving to: ‘united_kingdom-latest.osm.pbf’

united_kingdom-late 100%[===================>]   2.03G  14.3MB/s    in 5m 25s

2024-11-25 00:18:48 (6.41 MB/s) - ‘united_kingdom-latest.osm.pbf’ saved [2185131210/2185131210]

In [ ]:
# Install if needed
!pip install pyrosm

from pyrosm import OSM
import pandas as pd

# Initialize OSM object with the UK data
osm = OSM("united_kingdom-latest.osm.pbf")

# Let's look at a sample of different data types
# 1. Get a sample of buildings
buildings_df = osm.get_buildings()
print("\nBuildings sample (first 5 rows):")
print(buildings_df.head())
print(f"\nTotal buildings: {len(buildings_df)}")

# 2. Get main road network
roads_df = osm.get_network(network_type="driving")
print("\nRoads sample (first 5 rows):")
print(roads_df.head())
print(f"\nTotal road segments: {len(roads_df)}")

# 3. Get Points of Interest
pois_df = osm.get_pois()
print("\nPOIs by category:")
print(pois_df['amenity'].value_counts().head(10))

# Basic statistics about the data
print("\nData Overview:")
print("Buildings columns:", buildings_df.columns.tolist())
print("Roads columns:", roads_df.columns.tolist())
print("POIs columns:", pois_df.columns.tolist())

Collecting pyrosm
  Downloading pyrosm-0.6.2.tar.gz (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 37.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-rapidjson (from pyrosm)
  Downloading python_rapidjson-1.20-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Requirement already satisfied: setuptools>=18.0 in /usr/local/lib/python3.10/dist-packages (from pyrosm) (75.1.0)
Requirement already satisfied: geopandas>=0.12.0 in /usr/local/lib/python3.10/dist-packages (from pyrosm) (1.0.1)
Requirement already satisfied: shapely>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from pyrosm) (2.0.6)
Collecting cykhash (from pyrosm)
  Downloading cykhash-2.0.1.tar.gz (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 kB 3.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyrobuf (from pyrosm)
  Using cached pyrobuf-0.9.3-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from geopandas>=0.12.0->pyrosm) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.10/dist-packages (from geopandas>=0.12.0->pyrosm) (0.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas>=0.12.0->pyrosm) (24.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from geopandas>=0.12.0->pyrosm) (2.2.2)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from geopandas>=0.12.0->pyrosm) (3.7.0)
Requirement already satisfied: jinja2>=2.8 in /usr/local/lib/python3.10/dist-packages (from pyrobuf->pyrosm) (3.1.4)
Requirement already satisfied: cython>=0.23 in /usr/local/lib/python3.10/dist-packages (from pyrobuf->pyrosm) (3.0.11)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.8->pyrobuf->pyrosm) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas>=0.12.0->pyrosm) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas>=0.12.0->pyrosm) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas>=0.12.0->pyrosm) (2024.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from pyogrio>=0.7.2->geopandas>=0.12.0->pyrosm) (2024.8.30)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas>=0.12.0->pyrosm) (1.16.0)
Downloading python_rapidjson-1.20-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 62.1 MB/s eta 0:00:00
Building wheels for collected packages: pyrosm, cykhash
  Building wheel for pyrosm (pyproject.toml) ... done
  Created wheel for pyrosm: filename=pyrosm-0.6.2-cp310-cp310-linux_x86_64.whl size=7462962 sha256=55752494a10f632c4e670099e06f7350cdf6e5fd8663f15f12d3d430a8fc401e
  Stored in directory: /root/.cache/pip/wheels/18/21/22/b07b96a708420e351c553188667cfd6ebc7e78a011a8708cf4
  Building wheel for cykhash (pyproject.toml) ... done
  Created wheel for cykhash: filename=cykhash-2.0.1-cp310-cp310-linux_x86_64.whl size=3365962 sha256=70d995d44b9ac136ac7c745dba4b6cdb68224fc734a306636bb3fb46d9cdca83
  Stored in directory: /root/.cache/pip/wheels/ed/de/7a/4386df8e70276a0d2ec5e990db76b6c89889dc41cd627e1c14
Successfully built pyrosm cykhash
Installing collected packages: cykhash, python-rapidjson, pyrobuf, pyrosm
Successfully installed cykhash-2.0.1 pyrobuf-0.9.3 pyrosm-0.6.2 python-rapidjson-1.20

## Assess

Write a short paragraph summarising what you did in the Assess stage.

In [ ]:
# TODO: your answer here

## Address

In [ ]:
def estimate_students(latitude: float, longitude: float) -> float:
    """
    Args:
    latitude (float): The latitude coordinate.
    longitude (float): The longitude coordinate.

    Returns:
    float: Estimated share of students in that area (value between 0 and 1).
    """
    # TODO: implement
    return NotImplementedError


def estimate_something(latitude: float, longitude: float) -> float:
    #TODO: rename function
    """
    Args:
    latitude (float): The latitude coordinate.
    longitude (float): The longitude coordinate.

    Returns:
    float: Estimated value, percentage, probability, etc
    """
    # TODO: implement
    return NotImplementedError

Write a short paragraph summarising what you did in the Address stage.

In [ ]:
# TODO: your answer here

## Discussion

#### Story and structure

In [ ]:
# Marks awarded for inline explanation and structure, no need for answers here. Go over your notebook to make sure you explain what you did and why.

#### Design decisions

In [ ]:
# TODO: your answer here

#### Comparison

In [ ]:
# TODO: your answer here

#### Reusability

In [ ]:
# TODO: your answer here

# Task 2: miniproject (13 marks)

We expect your miniproject to be more advanced than the example project, and that's why we allocated more marks to it. The first 7 marks will be allocated similarly to Task 1.

6 remaining points are *bonus* - they will be allocated for going far beyond what you did in Task 1, either in data access, assess, address or story.

#### Choosing your topic

You are given a lot of flexibility in choosing a miniproject topic.

Some hints:
- Your project should be based on the Census, Price Paid, OSM and Election datasets.
- It's a good idea to pick something that you are interested in.
- Bear in mind there are no marks dedicated to your overall prediction accuracy, so there is no advantage to picking 'easy' topics. It is perfectly ok to not reach significant predictive power, as long as you followed the proper process.

Some guidelines:
- Do not make a miniproject that furthers discriminatory rhetoric. In general, avoid topics that could be insensitive. If in doubt, message Radzim Sendyka (and *cc* Christian Cabrera) to discuss if this applies to your idea.
- Please avoid any projects that would require approval from the ethics comittee.
- Pick the scope of your projects that will allow you to show your skills. Some projects might not be challenging enough while others might be hard to make any progress in. Don't be scared to report negative results.

Please email Radzim Sendyka (and *cc* Christian Cabrera) with your project idea when you begin working on it, so we can let you know about any potential concerns (eg. potentially insensive, too off-topic, too simple, too complex) as soon as we can. You can change the topic up to the submission deadline, but let us know again in cases of major changes.

Most of the advice from Task 1 still applies, particularly around using an online relational database, structuring your notebook, fynesse, access-assess-address, data readiness levels, hints.

Sources you may want to include in your data include:

  - UK Census Data
    - UK Census 2021 data [here](https://www.ons.gov.uk/search?topics=9731,6646,3845,9497,4262,4128,7755,4994,6885,9724,7367&filter=datasets) or [here](https://www.nomisweb.co.uk/sources/census_2021_bulk).
    - Historical Census data [here](https://www.ons.gov.uk/census/historiccensusdata).
    - Geographic coordinates of Census Output Areas [here](https://www.data.gov.uk/dataset/4d4e021d-fe98-4a0e-88e2-3ead84538537/output-areas-december-2021-boundaries-ew-bgc-v2).
  - Spatial data
    - You should already have a connection to OpenStreetMaps.
    - You might want to also download the entire map for England (or more) [here](https://download.openstreetmap.fr/extracts/) or [here](https://wiki.openstreetmap.org/wiki/Planet.osm).
  - Election data
    - Recent Election Results data [here](https://commonslibrary.parliament.uk/research-briefings/cbp-10009/)
    - Historical Election Results data [here](https://commonslibrary.parliament.uk/research-briefings/cbp-8647/#fullreport).
    - Lookup reference between Output Areas and Parliamentary Constituencies [here](https://geoportal.statistics.gov.uk/datasets/5968b5b2c0f14dd29ba277beaae6dec3_0/explore).
  - Price Paid Data
    - You should have this data already in your database.
  - OSM
    - You should know how to access this data from previous practicals.

Example ideas:

- Are areas correlated in terms of census results? If so, find the areas that are leading change, and the ones that are following.
- Which historical census variables used to predict election results in the past, but don't seem related anymore?
- Census results are only updated once a decade, but new roads and houses are built every year. Can census results, for example those relating to travel, be predicted from basic map information, such as street networks?
- Building new houses is our best way of tackling the housing crisis. Use the information on new builds in the house prices dataset to explore what factors drive new developments, and make predictions for where the next houses will be built.
- House styles differ a lot between regions and inhabitants. Can you make any predictions about the house or area simply from looking at it's geometric shape and orientation?

Note that the ideas are just a starting point question. You should include more in-depth investigations into the data, validate your findings where applicable, and prepare visualisations.

## Title and description

In [ ]:
# TODO: title your miniproject

In [ ]:
# TODO: provide a very brief description of the goals of your miniproject

## TODO: Your Project Goes Here

In [ ]:
%sql mariadb+pymysql://$username:$password@$url?local_infile=1
%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%sql SHOW databases

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
7 rows affected.

[('ads_2024',),
 ('information_schema',),
 ('innodb',),
 ('mysql',),
 ('performance_schema',),
 ('sys',),
 ('tmp',)]

In [ ]:
%%sql
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sql/magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
  File "/usr/local/lib/python3.10/dist-packages/sql/connection.py", line 82, in set
    raise ConnectionError(
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [ ]:
%%sql
USE `ads_2024`;

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
0 rows affected.

[]

In [ ]:
%%sql SHOW TABLES;

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
3 rows affected.

[('postcode_data',), ('pp_data',), ('prices_coordinates_data',)]

In [ ]:
# [1] price_paid data
first_5_rows = %sql SELECT * FROM `pp_data` LIMIT 5;
print(first_5_rows)

 * mariadb+pymysql://admin:***@database-ads-pz286.cgrre17yxw11.eu-west-2.rds.amazonaws.com?local_infile=1
5 rows affected.
+----------------------------------------+---------+------------------+----------+---------------+----------------+-------------+---------------------------------+-----------------------------------+---------------------+--------------+----------------+------------------+------------------+-------------------+---------------+-------+
|     transaction_unique_identifier      |  price  | date_of_transfer | postcode | property_type | new_build_flag | tenure_type | primary_addressable_object_name | secondary_addressable_object_name |        street       |   locality   |   town_city    |     district     |      county      | ppd_category_type | record_status | db_id |
+----------------------------------------+---------+------------------+----------+---------------+----------------+-------------+---------------------------------+-----------------------------------+---------------------+--------------+----------------+------------------+------------------+-------------------+---------------+-------+
| {EC7AD099-74F5-9200-E053-6C04A8C0E306} |  79000  |    2011-09-16    | PL1 5NN  |       F       |       N        |      L      |                1                |         GROUND FLOOR FLAT         | ST BARNABAS TERRACE |              |    PLYMOUTH    | CITY OF PLYMOUTH | CITY OF PLYMOUTH |         A         |       A       |   1   |
| {EC7AD099-F60D-9200-E053-6C04A8C0E306} | 1415000 |    2011-07-29    |  W4 4LD  |       S       |       N        |      F      |                4                |                                   |  SUTTON LANE NORTH  |              |     LONDON     |     HOUNSLOW     |  GREATER LONDON  |         A         |       A       |   2   |
| {EC7AD09A-0258-9200-E053-6C04A8C0E306} |  74000  |    2011-06-09    | NR30 4JG |       T       |       N        |      F      |                14               |                                   |    ESTCOURT ROAD    |              | GREAT YARMOUTH |  GREAT YARMOUTH  |     NORFOLK      |         A         |       A       |   3   |
| {EC7AD09A-42CC-9200-E053-6C04A8C0E306} |  130000 |    2011-04-15    |  S6 4BB  |       S       |       N        |      F      |                52               |                                   |     WORRALL ROAD    |              |   SHEFFIELD    |    SHEFFIELD     | SOUTH YORKSHIRE  |         A         |       A       |   4   |
| {60436C45-54F8-4765-A89C-53CEC51F1008} |  125000 |    2011-09-08    | SA44 6DS |       D       |       N        |      F      |             AFALLON             |                                   |                     | BRYNHOFFNANT |   LLANDYSUL    |    CEREDIGION    |    CEREDIGION    |         A         |       A       |   5   |
+----------------------------------------+---------+------------------+----------+---------------+----------------+-------------+---------------------------------+-----------------------------------+---------------------+--------------+----------------+------------------+------------------+-------------------+---------------+-------+

In [ ]:
new = get_df('TS013', level='ltla')

new = new.drop(['date', 'geography', 'geography code'], axis=1, errors='ignore')

Files already exist at: census2021-ts013.

In [ ]:
# sum all but first column in each row
new['total'] = new.iloc[:, 1:].sum(axis=1)

In [ ]:
new[['total','Passports held: Total: All usual residents; measures: Value']]

      total  Passports held: Total: All usual residents; measures: Value
0    166460                                              92336
1    273781                                             143925
2    246199                                             136529
3    365566                                             196601
4    203911                                             107798
..      ...                                                ...
326  167170                                              92273
327  174944                                              92960
328  311576                                             159590
329  242613                                             133169
330  110030                                              58840

[331 rows x 2 columns]

## Conclusions

The below code is for marking purpuses only, and not part of your project. It helps us gather the data we need without asking you for database credentials, and scouring github pages. This is mandatory. If the code does not work for you, let us know immediately.

1) Please re-run the code from Practical 1 to help us see the contents of your database. We recommend you include all data sources there, but some smaller inputs are fine to use as files.

In [ ]:
tables = %sql SHOW TABLES;

for row in tables:
    table_name = row[0]
    print(f"\nTable: {table_name}")

    table_status = %sql SHOW TABLE STATUS LIKE '{table_name}';
    approx_row_count = table_status[0][4] if table_status else 'Unable to fetch row count'
    print("\nApprox Row Count:", approx_row_count//100000/10, "M")

    first_5_rows = %sql SELECT * FROM `{table_name}` LIMIT 5;
    print(first_5_rows)

    indices = %sql SHOW INDEX FROM `{table_name}`;
    if indices:
        print("\nIndices:")
        for index in indices:
            print(f" - {index[2]} ({index[10]}): Column {index[4]}")
    else:
        print("\nNo indices set on this table.")

UsageError: Line magic function `%sql` not found.

2) Please paste a link to your fynesse library below, and make sure it's publically accessible. Also run the code below, and make sure it worked, printing out the contents of your library.

In [ ]:
fynesse_url = '<your-url-library-here>'

In [ ]:
import fynesse
import os

print('FYNESSE STRUCTURE:')
package_path = os.path.dirname(fynesse.__file__)
for root, dirs, files in os.walk(package_path):
    level = root.replace(package_path, '').count(os.sep)
    indent = ' ' * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    sub_indent = ' ' * 4 * (level + 1)
    for f in files:
        print(f"{sub_indent}{f}")

print('FILE CONTENTS')
for root, dirs, files in os.walk(package_path):
    for file in files:
        file_path = os.path.join(root, file)
        print(f"--- Contents of {file_path} ---\n")
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                print(f.read())
        except Exception as e:
            print(f"Could not read {file_path}: {e}")
        print("\n" + "-" * 50 + "\n")